### ISSUE TITLE
Need a Zipper.set

### ISSUE THREAD

**Issue by Kurren123** [turboMaCk/non-empty-list-alias#19]
Could also be called `Zipper.update` or something similar, but I need something which sets the current focus at the zipper, throwing away the old one. Something like:

```elm
set : a -> Zipper a -> Zipper a
set a (Zipper b f n) = 
    (Zipper b a n)
```

I can make do with `Zipper.custom` for now, but just thought I'd let you know. Happy to make a PR when I have a moment, let me know if you'd like that.

**Comment by turboMaCk** [comment]
Thanks for the issue. I've also already hit a case where I needed this myself https://github.com/turboMaCk/non-empty-list-alias/issues/16

**Comment by turboMaCk** [comment]
1.1.0 includes `Zipper.update` function which is slightly more modular than `set`. `Zipper.update (always foo)` is equivalent to `Zipper.set foo`.
